import tiktoken
import torch

from llm.models import GPTConfig, GPTModel, generate
from llm.tokenizer import text_to_token_ids, token_ids_to_text


def llm_call(
    prompt: str,
    model: GPTModel,
    config: GPTConfig,
    tokenizer: tiktoken.Encoding,
    device: torch.device,
    eos_id: int
) -> str:
    """Call the LLM model with a given prompt and return the response.

    :param prompt: The input prompt to send to the LLM model.
    :param model: The LLM model to use for generating the response.
    :param config: The configuration for the LLM model.
    :param tokenizer: The tokenizer to use for encoding and decoding text.
    :param device: The device (CPU or GPU) to run the model on.
    :param eos_id: The end-of-sequence token ID for the model.
    :return: The response generated by the LLM model.
    """
    prompt_token = text_to_token_ids(prompt, tokenizer).to(device)

    response_token = generate(
        model=model,
        idx=prompt_token,
        max_new_tokens=256,
        context_size=config.context_length,
        eos_id=eos_id,
        exclude_input=True,
    )
    return token_ids_to_text(response_token, tokenizer)

if __name__ == "__main__":
    from pathlib import Path

    from reasoning_from_scratch.qwen3 import Qwen3Tokenizer

    from llm.models import LLMGPTModel, LLMQwen3Model
    from llm.utils import get_device

    device = get_device()

    #tokenizer = tiktoken.get_encoding("gpt2")
    #gpt_model = LLMGPTModel()
    #model_name = "gpt2-xl-alpaca-sft.pth"
    #eos_id = 50256

    tokenizer_path = Path("data/qwen3/tokenizer-base.json")
    tokenizer = Qwen3Tokenizer(tokenizer_file_path=tokenizer_path)
    gpt_model = LLMQwen3Model()
    model_name = "qwen3-0.6B-base.pth"
    eos_id = tokenizer.eos_token_id

    gpt_model.load(model_name, device)

    prompt = """
    Below is an instruction that describes a task.
    Write a response that appropriately completes the request.

    ### Instruction:
    What is the capital of Sweden?
    """

    response = llm_call(prompt, gpt_model.model, gpt_model.config, tokenizer, device, eos_id)
    print(response)
