"""Usage example of the LLM model call."""
import tiktoken
import torch

from llm.model import GPTConfig, GPTModel, generate, load_model
from llm.tokenizer import text_to_token_ids, token_ids_to_text


def llm_call(
    prompt: str,
    model: GPTModel,
    config: GPTConfig,
    tokenizer: tiktoken.Encoding,
    device: torch.device,
) -> str:
    """Call the LLM model with a given prompt and return the response.

    :param prompt: The input prompt to send to the LLM model.
    :param model: The LLM model to use for generating the response.
    :param config: The configuration for the LLM model.
    :param tokenizer: The tokenizer to use for encoding and decoding text.
    :param device: The device (CPU or GPU) to run the model on.
    :return: The response generated by the LLM model.
    """
    prompt_token = text_to_token_ids(prompt, tokenizer).to(device)

    response_token = generate(
        model=model,
        idx=prompt_token,
        max_new_tokens=256,
        context_size=config.context_length,
        eos_id=50256,
        exclude_input=True,
    )
    return token_ids_to_text(response_token, tokenizer)

if __name__ == "__main__":
    from llm.utils import get_device

    device = get_device()
    tokenizer = tiktoken.get_encoding("gpt2")
    model, config = load_model("gpt2-xl-alpaca-sft", device=device)

    prompt = """
    Below is an instruction that describes a task.
    Write a response that appropriately completes the request.

    ### Instruction:
    What is the capital of Sweden?
    """

    response = llm_call(prompt, model, config, tokenizer, device)
    print(response)
